# 1 - Configuração do ambiente e base de dados de desenvolvimento

* Instalação do módulo jupysql

In [ ]:
!pip install jupysql

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.8/192.8 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 kB 5.3 MB/s eta 0:00:00


* Carregamento da extensão *sql*  

In [ ]:
%load_ext sql

* Conexão à base base de dados(se não existir é criada):



In [ ]:
%sql sqlite:///Minha_BD_Testes.db

Connecting to 'sqlite:///Minha_BD_Testes.db'

* Configurações

In [ ]:
%config SqlMagic.displaylimit = None
%sql PRAGMA foreign_keys = ON

# 2 - Implementação do modelo de dados

## Tabela *Produtos*


a) Definição da tabela "Clientes"
  
*%%sql  
CREATE TABLE IF NOT EXISTS produtos (  
    id INTEGER PRIMARY KEY,  
    nome TEXT ,  
    preco REAL,  
    unidades INTEGER  
);*  
  
*DROP TABLE IF EXISTS produtos;*  

No SQLite, o tipo TEXT pode armazenar até 2^31 - 1 bytes, ou seja, 2.147.483. 647 bytes (aproximadamente 2 GB) de dados.  

b) Verificar se a tabela existe na base de dados  
  *SELECT name FROM sqlite_master WHERE type="produtos";*    

c) Popular a tabela "Produtos"(através da instrução *DML insert*)  
*INSERT INTO produtos (id,nome, preco, unidades) VALUES (1,'Notebook', 3500.00, 10);  
INSERT INTO produtos (id,nome, preco, unidades) VALUES (2,'Smartphone', 2500.00, 20);  
INSERT INTO produtos (id,nome, preco, unidades) VALUES (3,'Mouse', 50.00, 100);  
INSERT INTO produtos (id,nome, preco, unidades) VALUES (4,'Teclado', 120.00, 50);*  

In [ ]:
%%sql
CREATE TABLE produtos (
numero INTEGER,
nome text ,
preco real,
unidades INteger
)

Running query in 'sqlite:///Minha_BD_Testes.db'

++
||
++
++

In [ ]:
%%sql
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (1,'Notebook',     3500.00, 10);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (2,'Smartphone',   2500.00, 20);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (3,'Mouse',          50.00, 100);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (4,'Teclado',       120.00, 50);

INSERT INTO produtos (numero,nome, preco, unidades) VALUES (5,'HardDosk SSS',     160,   0);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (6,'SmartWatch',      null, 120);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (7,'Monitor Y-Ultra',  480, 210);
INSERT INTO produtos (numero, preco, unidades) VALUES (8, 780, 520);

Running query in 'sqlite:///Minha_BD_Testes.db'

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

++
||
++
++

d) Efetuar uma consulta à tabela "Produtos"

In [ ]:
%%sql
SELECT * FROM produtos

Running query in 'sqlite:///Minha_BD_Testes.db'

+--------+------------+--------+----------+
| numero |    nome    | preco  | unidades |
+--------+------------+--------+----------+
|   1    |  Notebook  | 3500.0 |    10    |
|   2    | Smartphone | 2500.0 |    20    |
|   3    |   Mouse    |  50.0  |   100    |
|   4    |  Teclado   | 120.0  |    50    |
|   1    |  Notebook  | 3500.0 |    10    |
|   2    | Smartphone | 2500.0 |    20    |
|   3    |   Mouse    |  50.0  |   100    |
|   4    |  Teclado   | 120.0  |    50    |
+--------+------------+--------+----------+

e) Através de uma consulta selecionar os produtos com preço igual a 50

In [ ]:
%%sql
SELECT *
FROM produtos
where preco=50

Running query in 'sqlite:///Minha_BD_Testes.db'

+--------+-------+-------+----------+
| numero |  nome | preco | unidades |
+--------+-------+-------+----------+
|   3    | Mouse |  50.0 |   100    |
|   3    | Mouse |  50.0 |   100    |
+--------+-------+-------+----------+

f) Através de uma consulta selecionar os produtos com preço igual a 50 e com 100 unidades

In [ ]:
%%sql
SELECT *
FROM produtos
where preco=50
AND unidades=100

Running query in 'sqlite:///Minha_BD_Testes.db'

+--------+-------+-------+----------+
| numero |  nome | preco | unidades |
+--------+-------+-------+----------+
|   3    | Mouse |  50.0 |   100    |
|   3    | Mouse |  50.0 |   100    |
+--------+-------+-------+----------+

g) Extrair o nome dos produtos que custam 10€, 20 € ou 50€ ?

h) Determinar os vários preços que existem na tabela *Produtos*

i) Apresentar os atributos/campos: Nome e Unidades dos produtos com preço inferior a 100€ e a quantidade de unidades dísponiveis tem de ser superior a 10 e inferior a 100.

j) Apresentar o nome dos produtos sem preço definido

k) Apresentar o nome dos produtos com preço definido

## Tabela *Produtos* com chave primária

a) Eliminar a tabela "Produtos" da base de dados e recriar a tabela com as seguintes definições:     

*DROP TABLE produtos;*  

*CREATE TABLE IF NOT EXISTS produtos (  
id INTEGER PRIMARY KEY AUTOINCREMENT,  
nome TEXT NOT NULL,  
preco REAL NOT NULL,  
unidades INTEGER  
);*    


b) Popular novamente a tabela "Produtos"  
*INSERT INTO produtos (nome, preco, unidades) VALUES ('Notebook', 3500.00, 10);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Smartphone', 2500.00, 20);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Mouse', 50.00, 100);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Teclado', 120.00, 50);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('HardDosk SSS', 160, 0);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('SmartWatch', null,120);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Monitor Y-Ultra', 480,210);  
INSERT INTO produtos (preco, unidades) VALUES (780, 520);*    

## Tabela *Categorias*

a) Definir a tabela "Categorias"  

In [ ]:
%%sql
CREATE TABLE Categorias (
    id_categoria INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL
);

b) Popular a tabela "Categorias"     

In [ ]:
%%sql
INSERT INTO Categorias (nome) VALUES ('Eletrónica');
INSERT INTO Categorias (nome) VALUES ('Roupa');
INSERT INTO Categorias (nome) VALUES ('Calçado');
INSERT INTO Categorias (nome) VALUES ('Móveis');


c) Determinar a quantidade de registos na tabela *Categorias*

## Tabela *Produtos* com chave estrangeira

a) Redefinir a tabela "PRODUTOS", agora com a nova coluna *ID_CATEGORIA*: chave estrangeira para "CATEGORIA.ID_CATEGORIA"

*CREATE TABLE IF NOT EXISTS produtos (  
id INTEGER PRIMARY KEY,  
nome TEXT ,  
preco REAL,  
unidades INTEGER,  
id_categoria INTEGER,  
FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)  
);*  

b) Popular a tabela "PRODUTOS" de acordo com a nova estrutura

c) Através de uma consulta apresentar o nome do produto e nome da categoria dos produtos com mais de 100 unidades em *stock*

## Tabela *Fornecedores*

a) Definir a tabela "Fornecedores"  
*CREATE TABLE Fornecedores (  
    id_fornecedor INTEGER PRIMARY KEY AUTOINCREMENT,  
    nome VARCHAR(50) NOT NULL,   
    endereco VARCHAR(128),  
    cidade VARCHAR(20),  
    pais   VARCHAR(30),  
    telefone VARCHAR(16),  
    email VARCHAR(30)  
);*  

b) Popular a tabela "Fornecedores"  
*INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)   
VALUES ('Tech Solutions', 'Av. Paulista, 1000', 'São Paulo', 'Brasil', '+55 11   98765-4321', 'contato@techsolutions.com');*  

*INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)   
VALUES ('Global Supplies', '123 Main St', 'New York', 'EUA', '+1 212-555-7890',   'sales@globalsupplies.com');*    

*INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)   
VALUES ('ElectroParts', 'Calle Mayor, 45', 'Madrid', 'Espanha', '+34 91 123   4567', 'info@electroparts.es');*    

*INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)   
VALUES ('MegaCom', 'Rua das Flores, 500', 'Lisboa', 'Portugal', '+351 21 456   7890', 'support@megacom.pt');*    

*INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email   
VALUES ('Fast Logistics', 'Jalan Sudirman, 12', 'Jacarta', 'Indonésia', '+62 21   8765 4321', 'contact@fastlogistics.co.id');*  



c) Redefinir a tabela "PRODUTOS", agora com a nova coluna *ID_FORNECEDOR*: chave estrangeira para "FORNECEDORES.ID_FORNECEDOR"  

*CREATE TABLE IF NOT EXISTS produtos (  
id INTEGER PRIMARY KEY,  
nome TEXT ,  
preco REAL,  
unidades INTEGER,  
id_categoria INTEGER,
id_fornecedor INTEGER,  
FOREIGN KEY (id_categoria) REFERENCES CATEGORIAS(id_categoria),  
FOREIGN KEY (id_fornecedor) REFERENCES FORNECEDORES(id_fornecedor)    
);*  

d) Popular a tabela "PRODUTOS" de acordo com a nova estrutura

e) Através de uma consulta apresentar o nome do produto e nome do fornecedor dos produtos em que o fornecedor reside na Indonésia

f) Através de uma consulta selecionar os fornecedores residentes na Espanha

g) Através de uma consulta selecionar os fornecedores residentes na Espanha e em Madrid