# 1 - Configuração do ambiente e base de dados de desenvolvimento

* Instalação do módulo jupysql

In [ ]:
INSTALL = False
if INSTALL:
    !pip install jupysql

* Carregamento da extensão *sql*

In [47]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


* Conexão à base base de dados(se não existir é criada):



In [3]:
%sql sqlite:///Exercicio_Produtos.sqlite

Connecting to 'sqlite:///Exercicio_Produtos.sqlite'

* Configurações

In [46]:
%config SqlMagic.displaylimit = None
%sql PRAGMA foreign_keys = ON

displaylimit: Value None will be treated as 0 (no limit)

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

# 2 - Implementação do modelo de dados

## Tabela *Produtos*


a) Definição da tabela `produtos`


```sql
DROP TABLE IF EXISTS produtos;
```


```sql  
CREATE TABLE IF NOT EXISTS produtos (  
    id INTEGER PRIMARY KEY,  
    nome TEXT ,  
    preco REAL,  
    unidades INTEGER  
);
```

No SQLite, o tipo TEXT pode armazenar até 2^31 - 1 bytes, ou seja, 2.147.483. 647 bytes (aproximadamente 2 GB) de dados.  

b) Verificar se a tabela existe na base de dados  
```sql
SELECT name FROM sqlite_master WHERE type="produtos";
```  

c) Popular a tabela `produtos` (através da instrução *DML insert*)  

```sql
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (1,'Notebook',     3500.00, 10);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (2,'Smartphone',   2500.00, 20);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (3,'Mouse',          50.00, 100);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (4,'Teclado',       120.00, 50);

INSERT INTO produtos (numero,nome, preco, unidades) VALUES (5,'HardDosk SSS',     160,   0);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (6,'SmartWatch',      null, 120);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (7,'Monitor Y-Ultra',  480, 210);
INSERT INTO produtos (numero, preco, unidades)      VALUES (8, 780, 520);
```

In [5]:
%%sql
DROP TABLE IF EXISTS produtos;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

In [6]:
%%sql
CREATE TABLE produtos (
    numero INTEGER,
    nome text ,
    preco real,
    unidades INteger
)

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

In [7]:
%%sql
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (1,'Notebook', 3500.00, 10);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (2,'Smartphone', 2500.00, 20);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (3,'Mouse', 50.00, 100);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (4,'Teclado', 120.00, 50);

INSERT INTO produtos (numero,nome, preco, unidades) VALUES (5,'HardDosk SSS', 160, 0);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (6,'SmartWatch', null,120);
INSERT INTO produtos (numero,nome, preco, unidades) VALUES (7,'Monitor Y-Ultra', 480, 210);
INSERT INTO produtos (numero, preco, unidades) VALUES (8, 780, 520);


Running query in 'sqlite:///Exercicio_Produtos.sqlite'

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

++
||
++
++

d) Efetuar uma consulta à tabela `produtos`

In [8]:
%%sql
SELECT * FROM produtos;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+--------+-----------------+--------+----------+
| numero |       nome      | preco  | unidades |
+--------+-----------------+--------+----------+
|   1    |     Notebook    | 3500.0 |    10    |
|   2    |    Smartphone   | 2500.0 |    20    |
|   3    |      Mouse      |  50.0  |   100    |
|   4    |     Teclado     | 120.0  |    50    |
|   5    |   HardDosk SSS  | 160.0  |    0     |
|   6    |    SmartWatch   |  None  |   120    |
|   7    | Monitor Y-Ultra | 480.0  |   210    |
|   8    |       None      | 780.0  |   520    |
+--------+-----------------+--------+----------+

e) Através de uma consulta selecionar os produtos com preço igual a 50

In [9]:
%%sql
SELECT * 
FROM produtos 
WHERE unidades = 50;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+--------+---------+-------+----------+
| numero |   nome  | preco | unidades |
+--------+---------+-------+----------+
|   4    | Teclado | 120.0 |    50    |
+--------+---------+-------+----------+

f) Através de uma consulta selecionar os produtos com preço igual a 50 e com 100 unidades

In [11]:
%%sql
SELECT *
FROM produtos
WHERE preco = 50
AND unidades = 100

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+--------+-------+-------+----------+
| numero |  nome | preco | unidades |
+--------+-------+-------+----------+
|   3    | Mouse |  50.0 |   100    |
+--------+-------+-------+----------+

g) Extrair o nome dos produtos que custam 10€, 20€ ou 50€ ?

In [12]:
%%sql
SELECT nome
FROM produtos
WHERE preco IN (10, 20, 50)

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+-------+
|  nome |
+-------+
| Mouse |
+-------+

g.2) Extrair o nome dos produtos que não custam 10€, 20 € ou 50€ ?

In [13]:
%%sql
SELECT nome
FROM produtos
WHERE preco NOT IN (10, 20, 50)

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+-----------------+
|       nome      |
+-----------------+
|     Notebook    |
|    Smartphone   |
|     Teclado     |
|   HardDosk SSS  |
| Monitor Y-Ultra |
|       None      |
+-----------------+

g.3) Extrair o nome dos produtos que custam entre 10€ e 50€ ?

In [14]:
%%sql
SELECT nome
FROM produtos
WHERE preco BETWEEN 10 AND 50;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+-------+
|  nome |
+-------+
| Mouse |
+-------+

h) Determinar os vários preços que existem na tabela `produtos`

In [15]:
%%sql
SELECT DISTINCT preco, nome FROM produtos ORDER BY preco DESC;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+--------+-----------------+
| preco  |       nome      |
+--------+-----------------+
| 3500.0 |     Notebook    |
| 2500.0 |    Smartphone   |
| 780.0  |       None      |
| 480.0  | Monitor Y-Ultra |
| 160.0  |   HardDosk SSS  |
| 120.0  |     Teclado     |
|  50.0  |      Mouse      |
|  None  |    SmartWatch   |
+--------+-----------------+

---

## Tabela *Produtos* com chave primária

a) Eliminar a tabela `produtos` da base de dados e recriar a tabela com as seguintes definições:     
```sql
CREATE TABLE IF NOT EXISTS produtos (  
    id INTEGER PRIMARY KEY AUTOINCREMENT,  
    nome TEXT NOT NULL,  
    preco REAL NOT NULL,  
    unidades INTEGER  
);
```

In [16]:
%%sql
DROP TABLE produtos;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

In [17]:
%%sql
CREATE TABLE IF NOT EXISTS produtos (  
    id INTEGER PRIMARY KEY AUTOINCREMENT,  
    nome TEXT NOT NULL,
    preco REAL NOT NULL,
    unidades INTEGER  
);

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

h) Popular novamente a tabela `produtos`  
```sql
INSERT INTO produtos (nome, preco, unidades) VALUES ('Notebook', 3500.00, 10);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Smartphone', 2500.00, 20);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Mouse', 50.00, 100);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Teclado', 120.00, 50);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('HardDosk SSS', 160, 0);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('SmartWatch', null,120);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Monitor Y-Ultra', 480,210);  
INSERT INTO produtos (preco, unidades) VALUES (780, 520);
```  

In [18]:
%%sql
INSERT INTO produtos (nome, preco, unidades) VALUES ('Notebook', 3500.00, 10);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Smartphone', 2500.00, 20);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Mouse', 50.00, 100);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Teclado', 120.00, 50);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('HardDosk SSS', 160, 0);  
-- INSERT INTO produtos (nome, preco, unidades) VALUES ('SmartWatch', null,120);  
INSERT INTO produtos (nome, preco, unidades) VALUES ('Monitor Y-Ultra', 480,210);  
-- INSERT INTO produtos (preco, unidades) VALUES (780, 520);

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

++
||
++
++

---

## Tabela *Categorias*

a) Definir a tabela `categorias`

In [19]:
%%sql
DROP TABLE IF EXISTS categorias;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

In [20]:
%%sql
CREATE TABLE categorias (
    id_categoria INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL
);

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

b) Popular a tabela `categorias`

In [21]:
%%sql
INSERT INTO categorias (nome) VALUES ('Eletrónica');
INSERT INTO categorias (nome) VALUES ('Roupa');
INSERT INTO categorias (nome) VALUES ('Calçado');
INSERT INTO categorias (nome) VALUES ('Móveis');

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

++
||
++
++

c) Determinar a quantidade de registos na tabela `categorias`

In [22]:
%%sql
SELECT COUNT(*) as "número de categorias" FROM categorias;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+----------------------+
| número de categorias |
+----------------------+
|          4           |
+----------------------+

## Tabela `produtos` com chave estrangeira

a) Redefinir a tabela `produtos`, agora com a nova coluna `id_categoria`: chave estrangeira para "`categoria.id_categoria`"

```sql
CREATE TABLE IF NOT EXISTS produtos (  
    id INTEGER PRIMARY KEY,  
    nome TEXT ,  
    preco REAL,  
    unidades INTEGER,  
    id_categoria INTEGER,  
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)  
);
```


In [24]:
%%sql
DROP TABLE IF EXISTS produtos;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

In [25]:
%%sql
CREATE TABLE IF NOT EXISTS produtos (  
    id INTEGER PRIMARY KEY,  
    nome TEXT ,  
    preco REAL,  
    unidades INTEGER,  
    id_categoria INTEGER,  
    FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria)  
);

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

b) Popular a tabela `produtos` de acordo com a nova estrutura

In [26]:
%%sql
SELECT * FROM categorias;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+--------------+------------+
| id_categoria |    nome    |
+--------------+------------+
|      1       | Eletrónica |
|      2       |   Roupa    |
|      3       |  Calçado   |
|      4       |   Móveis   |
+--------------+------------+

In [27]:
%%sql
INSERT INTO produtos (nome, preco, unidades, id_categoria) VALUES ('Notebook',   3500.00, 10, 1);  
INSERT INTO produtos (nome, preco, unidades, id_categoria) VALUES ('Smartphone', 2500.00, 20, 1);  
INSERT INTO produtos (nome, preco, unidades, id_categoria) VALUES ('Mouse',        50.00, 100, 1);  
INSERT INTO produtos (nome, preco, unidades, id_categoria) VALUES ('Teclado',     120.00, 50, 1);  
INSERT INTO produtos (nome, preco, unidades, id_categoria) VALUES ('HardDosk SSS', 160, 0, 1);  
INSERT INTO produtos (nome, preco, unidades, id_categoria) VALUES ('SmartWatch', 350, 120, 1);  
INSERT INTO produtos (nome, preco, unidades, id_categoria) VALUES ('Monitor Y-Ultra', 480, 210, 1);  
INSERT INTO produtos (nome, preco, unidades, id_categoria) VALUES ('Smart Glasses', 780, 2, 1);

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

++
||
++
++

c) Através de uma consulta apresentar o nome do produto e nome da categoria dos produtos com mais de 100 unidades em stock

In [32]:
%%sql
SELECT 
    produtos.nome AS produto, produtos.preco, categorias.nome AS categoria
    
FROM produtos, categorias

WHERE 
    produtos.id_categoria = categorias.id_categoria AND
    produtos.unidades > 100

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+-----------------+-------+------------+
|     produto     | preco | categoria  |
+-----------------+-------+------------+
|    SmartWatch   | 350.0 | Eletrónica |
| Monitor Y-Ultra | 480.0 | Eletrónica |
+-----------------+-------+------------+

In [33]:
%%sql
SELECT produtos.nome AS produto, categorias.nome AS categoria
FROM produtos
JOIN categorias ON produtos.id_categoria = categorias.id_categoria
WHERE produtos.unidades > 100

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+-----------------+------------+
|     produto     | categoria  |
+-----------------+------------+
|    SmartWatch   | Eletrónica |
| Monitor Y-Ultra | Eletrónica |
+-----------------+------------+

## Tabela `fornecedores`

a) Definir a tabela `fornecedores`  
```sql
CREATE TABLE fornecedores (  
    id_fornecedor INTEGER PRIMARY KEY AUTOINCREMENT,  
    nome VARCHAR(50) NOT NULL,   
    endereco VARCHAR(128),  
    cidade VARCHAR(20),  
    pais   VARCHAR(30),  
    telefone VARCHAR(16),  
    email VARCHAR(30)  
);
```

In [34]:
%%sql
DROP TABLE IF EXISTS fornecedores;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

In [35]:
%%sql
CREATE TABLE Fornecedores (  
    id_fornecedor INTEGER PRIMARY KEY AUTOINCREMENT,  
    nome VARCHAR(50) NOT NULL,   
    endereco VARCHAR(128),  
    cidade VARCHAR(20),  
    pais   VARCHAR(30),  
    telefone VARCHAR(16),  
    email VARCHAR(30)  
);

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

b) Popular a tabela `fornecedores` 

```sql
INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)
VALUES ('Tech Solutions', 'Av. Paulista, 1000', 'São Paulo', 'Brasil', '+55 11   98765-4321', 'contato@techsolutions.com');

INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)
VALUES ('Global Supplies', '123 Main St', 'New York', 'EUA', '+1 212-555-7890',   'sales@globalsupplies.com');

INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)
VALUES ('ElectroParts', 'Calle Mayor, 45', 'Madrid', 'Espanha', '+34 91 123   4567', 'info@electroparts.es');

INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)
VALUES ('MegaCom', 'Rua das Flores, 500', 'Lisboa', 'Portugal', '+351 21 456   7890', 'support@megacom.pt');

INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)
VALUES ('Fast Logistics', 'Jalan Sudirman, 12', 'Jacarta', 'Indonésia', '+62 21   8765 4321', 'contact@fastlogistics.co.id');
```

In [36]:
%%sql
INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)
VALUES ('Tech Solutions', 'Av. Paulista, 1000', 'São Paulo', 'Brasil', '+55 11   98765-4321', 'contato@techsolutions.com');

INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)   
VALUES ('Global Supplies', '123 Main St', 'New York', 'EUA', '+1 212-555-7890',   'sales@globalsupplies.com');

INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)   
VALUES ('ElectroParts', 'Calle Mayor, 45', 'Madrid', 'Espanha', '+34 91 123   4567', 'info@electroparts.es');

INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)   
VALUES ('MegaCom', 'Rua das Flores, 500', 'Lisboa', 'Portugal', '+351 21 456   7890', 'support@megacom.pt');

INSERT INTO Fornecedores (nome, endereco, cidade, pais, telefone, email)
VALUES ('Fast Logistics', 'Jalan Sudirman, 12', 'Jacarta', 'Indonésia', '+62 21   8765 4321', 'contact@fastlogistics.co.id');

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

++
||
++
++

c) Redefinir a tabela `produtos`, agora com a nova coluna `id_fornecedor`: chave estrangeira para `fornecedores.id_fornecedor`  

```sql
DROP TABLE IF EXISTS produtos;

CREATE TABLE IF NOT EXISTS produtos (  
    id INTEGER PRIMARY KEY,  
    nome TEXT ,  
    preco REAL,  
    unidades INTEGER,  
    id_categoria INTEGER,
    id_fornecedor INTEGER,  
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIAS(id_categoria),  
    FOREIGN KEY (id_fornecedor) REFERENCES FORNECEDORES(id_fornecedor)    
);
```

In [37]:
%%sql
DROP TABLE produtos;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

In [38]:
%%sql
CREATE TABLE IF NOT EXISTS produtos (  
    id INTEGER PRIMARY KEY,  
    nome TEXT ,  
    preco REAL,  
    unidades INTEGER,  
    id_categoria INTEGER,
    id_fornecedor INTEGER,  
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIAS(id_categoria),  
    FOREIGN KEY (id_fornecedor) REFERENCES FORNECEDORES(id_fornecedor)    
);

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

++
||
++
++

d) Popular a tabela `produtos` de acordo com a nova estrutura

In [39]:
%%sql
SELECT id_fornecedor, nome, pais FROM fornecedores;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+---------------+-----------------+-----------+
| id_fornecedor |       nome      |    pais   |
+---------------+-----------------+-----------+
|       1       |  Tech Solutions |   Brasil  |
|       2       | Global Supplies |    EUA    |
|       3       |   ElectroParts  |  Espanha  |
|       4       |     MegaCom     |  Portugal |
|       5       |  Fast Logistics | Indonésia |
+---------------+-----------------+-----------+

In [40]:
%%sql
SELECT id_categoria,nome FROM categorias;

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+--------------+------------+
| id_categoria |    nome    |
+--------------+------------+
|      1       | Eletrónica |
|      2       |   Roupa    |
|      3       |  Calçado   |
|      4       |   Móveis   |
+--------------+------------+

In [41]:
%%sql
INSERT INTO produtos (nome, preco, unidades, id_categoria, id_fornecedor)
VALUES ('Notebook', 3500.00, 10    , 1, 1);

INSERT INTO produtos (nome, preco, unidades, id_categoria, id_fornecedor) 
VALUES ('Smartphone', 2500.00, 20  , 1, 2);  

INSERT INTO produtos (nome, preco, unidades, id_categoria, id_fornecedor) 
VALUES ('Mouse', 50.00, 100        , 1, 3);  

INSERT INTO produtos (nome, preco, unidades, id_categoria, id_fornecedor) 
VALUES ('Teclado', 120.00, 50      , 1, 5);

INSERT INTO produtos (nome, preco, unidades, id_categoria, id_fornecedor) 
VALUES ('HardDosk SSS', 160, 0, 1, 4);

INSERT INTO produtos (nome, preco, unidades, id_categoria, id_fornecedor)
VALUES ('SmartWatch', 350, 120, 1, 4);

INSERT INTO produtos (nome, preco, unidades, id_categoria, id_fornecedor)
VALUES ('Monitor Y-Ultra', 480, 210, 1, 4);
INSERT INTO produtos (nome, preco, unidades, id_categoria, id_fornecedor)
VALUES ('Smart Glasses', 780, 2, 1, 4);

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

++
||
++
++

e) Através de uma consulta apresentar o nome do produto e nome do fornecedor dos produtos em que o fornecedor reside na Indonésia

In [42]:
%%sql
SELECT
    produtos.nome AS produto,
    fornecedores.nome AS fornecedor,
    fornecedores.pais AS pais

FROM 
    produtos, categorias, fornecedores

WHERE 
    produtos.id_fornecedor = fornecedores.id_fornecedor AND
    fornecedores.pais = 'Indonésia';

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+---------+----------------+-----------+
| produto |   fornecedor   |    pais   |
+---------+----------------+-----------+
| Teclado | Fast Logistics | Indonésia |
| Teclado | Fast Logistics | Indonésia |
| Teclado | Fast Logistics | Indonésia |
| Teclado | Fast Logistics | Indonésia |
+---------+----------------+-----------+

In [43]:
%%sql
SELECT
    produtos.nome AS produto,
    categorias.nome AS categoria,
    fornecedores.nome AS fornecedor,
    fornecedores.pais AS pais

FROM 
    produtos, categorias, fornecedores

WHERE 
    produtos.id_categoria = categorias.id_categoria AND
    produtos.id_fornecedor = fornecedores.id_fornecedor AND
    fornecedores.pais = 'Indonésia';

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+---------+------------+----------------+-----------+
| produto | categoria  |   fornecedor   |    pais   |
+---------+------------+----------------+-----------+
| Teclado | Eletrónica | Fast Logistics | Indonésia |
+---------+------------+----------------+-----------+

f) Através de uma consulta selecionar os fornecedores residentes na Espanha

In [44]:
%%sql
SELECT nome, pais FROM fornecedores WHERE pais = 'Indonésia';

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+----------------+-----------+
|      nome      |    pais   |
+----------------+-----------+
| Fast Logistics | Indonésia |
+----------------+-----------+

g) Através de uma consulta selecionar os fornecedores residentes na Espanha e em Madrid

In [45]:
%%sql
SELECT nome, pais FROM fornecedores WHERE pais = 'Espanha' and cidade = 'Madrid';

Running query in 'sqlite:///Exercicio_Produtos.sqlite'

+--------------+---------+
|     nome     |   pais  |
+--------------+---------+
| ElectroParts | Espanha |
+--------------+---------+

***
# end of doc