# docker-compose-oracle -Testado parcialmente
# https://hub.docker.com/r/gvenzl/oracle-xe

name: FundamentosSQL

services:
  oracle:
    image: gvenzl/oracle-xe # MAIS DE 3GB!!
    container_name: oracle_xe
    ports:
      - 1521:1521
    environment:
      # Database Admin User: system
      ORACLE_PASSWORD: oracle_password
      ORACLE_DATABASE: mydatabase #XEPDB1 # DEFAULT
      APP_USER: oracle_user
      APP_USER_PASSWORD: oracle_password
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - default

volumes:
  oracle_data:

networks:
  default:
    name: FundamentosSQL-network
    driver: bridge

