# docker-compose file for PostgreSQL, Adminer, and pgAdmin
name: FundamentosSQL

services:
  # Servidor 2: MySQL Configuration
  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql_data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Web Interfaces for Databases: vários
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default

  # Web Interfaces for Databases: MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8083:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_PORT: 3306
      TZ: ${TZ}
    depends_on:
      - mysql
    networks:
      - default


volumes:
  mysql_data:    # Servidor 2: MySQL


networks:
  default:
    name: sql-network
    #external: true # uncomment this on production
    driver: bridge